"""initial schema

Revision ID: 09f63e0bdf64
Revises: 
Create Date: 2026-09-14 09:26:11.923693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09f63e0bdf64'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('account_no', sa.String(length=64), nullable=False, comment='账户号'),
    sa.Column('type', sa.String(length=50), nullable=False, comment='类型：deposit/withdraw/trade/fee/dividend'),
    sa.Column('amount', sa.Float(), nullable=True, comment='金额'),
    sa.Column('balance_after', sa.Float(), nullable=True, comment='变更后余额'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述'),
    sa.Column('related_order_no', sa.String(length=64), nullable=True, comment='关联订单号'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='发生时间'),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('account_no', sa.String(length=64), nullable=False, comment='账户号'),
    sa.Column('account_type', sa.String(length=50), nullable=True, comment='账户类型：cash/margin'),
    sa.Column('balance', sa.Float(), nullable=True, comment='可用资金'),
    sa.Column('frozen_balance', sa.Float(), nullable=True, comment='冻结资金'),
    sa.Column('total_deposited', sa.Float(), nullable=True, comment='累计入金'),
    sa.Column('total_withdrawn', sa.Float(), nullable=True, comment='累计出金'),
    sa.Column('total_profit', sa.Float(), nullable=True, comment='累计盈亏'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='账户状态'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_no'),
    sqlite_autoincrement=True
    )
    op.create_table('backtest_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('backtest_id', sa.Integer(), nullable=False, comment='回测 ID'),
    sa.Column('total_return', sa.Float(), nullable=True, comment='总收益率'),
    sa.Column('annual_return', sa.Float(), nullable=True, comment='年化收益率'),
    sa.Column('sharpe_ratio', sa.Float(), nullable=True, comment='夏普比率'),
    sa.Column('sortino_ratio', sa.Float(), nullable=True, comment='索提诺比率'),
    sa.Column('calmar_ratio', sa.Float(), nullable=True, comment='卡尔玛比率'),
    sa.Column('max_drawdown', sa.Float(), nullable=True, comment='最大回撤'),
    sa.Column('max_drawdown_duration', sa.Integer(), nullable=True, comment='最大回撤持续时间（交易日）'),
    sa.Column('win_rate', sa.Float(), nullable=True, comment='胜率'),
    sa.Column('profit_factor', sa.Float(), nullable=True, comment='盈利因子'),
    sa.Column('avg_win', sa.Float(), nullable=True, comment='平均盈利'),
    sa.Column('avg_loss', sa.Float(), nullable=True, comment='平均亏损'),
    sa.Column('largest_win', sa.Float(), nullable=True, comment='最大单笔盈利'),
    sa.Column('largest_loss', sa.Float(), nullable=True, comment='最大单笔亏损'),
    sa.Column('total_trades', sa.Integer(), nullable=True, comment='总交易次数'),
    sa.Column('winning_trades', sa.Integer(), nullable=True, comment='盈利次数'),
    sa.Column('losing_trades', sa.Integer(), nullable=True, comment='亏损次数'),
    sa.Column('start_balance', sa.Float(), nullable=True, comment='起始资金'),
    sa.Column('end_balance', sa.Float(), nullable=True, comment='结束资金'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_table('backtest_trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('backtest_id', sa.Integer(), nullable=False, comment='回测 ID'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='股票代码'),
    sa.Column('date', sa.DateTime(), nullable=False, comment='交易日期'),
    sa.Column('direction', sa.String(length=10), nullable=False, comment='方向：buy/sell'),
    sa.Column('price', sa.Float(), nullable=False, comment='价格'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='数量'),
    sa.Column('commission', sa.Float(), nullable=True, comment='佣金'),
    sa.Column('slip', sa.Float(), nullable=True, comment='滑点'),
    sa.Column('pnl', sa.Float(), nullable=True, comment='盈亏'),
    sa.Column('equity', sa.Float(), nullable=True, comment='累计权益'),
    sa.Column('drawdown', sa.Float(), nullable=True, comment='当前回撤'),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_table('backtests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='回测名称'),
    sa.Column('strategy_id', sa.Integer(), nullable=False, comment='策略 ID'),
    sa.Column('code_list', sa.JSON(), nullable=True, comment='测试股票列表'),
    sa.Column('start_date', sa.DateTime(), nullable=False, comment='开始日期'),
    sa.Column('end_date', sa.DateTime(), nullable=False, comment='结束日期'),
    sa.Column('initial_capital', sa.Float(), nullable=True, comment='初始资金'),
    sa.Column('commission_rate', sa.Float(), nullable=True, comment='佣金率'),
    sa.Column('slip_rate', sa.Float(), nullable=True, comment='滑点率'),
    sa.Column('status', sa.String(length=50), nullable=True, comment='状态：pending/running/completed/failed'),
    sa.Column('progress', sa.Integer(), nullable=True, comment='进度：0-100'),
    sa.Column('params', sa.JSON(), nullable=True, comment='回测参数'),
    sa.Column('created_by', sa.String(length=100), nullable=True, comment='创建者'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='完成时间'),
    sa.Column('error_msg', sa.Text(), nullable=True, comment='错误信息'),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_table('calendar',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('trade_date', sa.DateTime(), nullable=False, comment='交易日期'),
    sa.Column('is_holiday', sa.Boolean(), nullable=True, comment='是否节假日'),
    sa.Column('market_status', sa.String(length=50), nullable=True, comment='市场状态：open/closed'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_date'),
    sqlite_autoincrement=True
    )
    op.create_table('equity_curves',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('backtest_id', sa.Integer(), nullable=False, comment='回测 ID'),
    sa.Column('date', sa.DateTime(), nullable=False, comment='日期'),
    sa.Column('equity', sa.Float(), nullable=True, comment='累计权益'),
    sa.Column('cumulative_return', sa.Float(), nullable=True, comment='累计收益率'),
    sa.Column('drawdown', sa.Float(), nullable=True, comment='当前回撤'),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_table('market_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='股票代码'),
    sa.Column('data_type', sa.Enum('quote', 'kline_1m', 'kline_5m', 'kline_15m', 'kline_30m', 'kline_1h', 'kline_4h', 'kline_1d', 'kline_1w', name='marketdatatype'), nullable=False, comment='数据类型'),
    sa.Column('timestamp', sa.DateTime(), nullable=False, comment='时间戳'),
    sa.Column('open', sa.Float(), nullable=True, comment='开盘价'),
    sa.Column('high', sa.Float(), nullable=True, comment='最高价'),
    sa.Column('low', sa.Float(), nullable=True, comment='最低价'),
    sa.Column('close', sa.Float(), nullable=False, comment='收盘价'),
    sa.Column('volume', sa.BigInteger(), nullable=True, comment='成交量'),
    sa.Column('amount', sa.Float(), nullable=True, comment='成交额'),
    sa.Column('open_interest', sa.Float(), nullable=True, comment='持仓量'),
    sa.Column('vwap', sa.Float(), nullable=True, comment='加权均价'),
    sa.Column('extra', sa.JSON(), nullable=True, comment='扩展数据'),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('order_no', sa.String(length=64), nullable=False, comment='订单号'),
    sa.Column('strategy_id', sa.Integer(), nullable=True, comment='策略 ID'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='股票代码'),
    sa.Column('direction', sa.Enum('buy', 'sell', name='orderdirection'), nullable=False, comment='交易方向'),
    sa.Column('order_type', sa.Enum('limit', 'market', name='ordertype'), nullable=True, comment='订单类型'),
    sa.Column('price', sa.Float(), nullable=True, comment='委托价格'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='委托数量'),
    sa.Column('filled_quantity', sa.Integer(), nullable=True, comment='成交数量'),
    sa.Column('avg_price', sa.Float(), nullable=True, comment='成交均价'),
    sa.Column('status', sa.Enum('pending', 'submitted', 'partially_filled', 'filled', 'cancelled', 'rejected', name='orderstatus'), nullable=True, comment='订单状态'),
    sa.Column('submit_time', sa.DateTime(), nullable=True, comment='提交时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('filled_time', sa.DateTime(), nullable=True, comment='成交时间'),
    sa.Column('reject_reason', sa.Text(), nullable=True, comment='拒绝原因'),
    sa.Column('extra', sa.JSON(), nullable=True, comment='扩展信息'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_no'),
    sqlite_autoincrement=True
    )
    op.create_table('positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='股票代码'),
    sa.Column('name', sa.String(length=100), nullable=True, comment='股票名称'),
    sa.Column('direction', sa.Enum('long', 'short', name='positiondirection'), nullable=True, comment='持仓方向'),
    sa.Column('quantity', sa.Integer(), nullable=True, comment='持仓数量'),
    sa.Column('avg_cost', sa.Float(), nullable=True, comment='持仓成本'),
    sa.Column('avg_price', sa.Float(), nullable=True, comment='持仓均价'),
    sa.Column('current_price', sa.Float(), nullable=True, comment='当前价格'),
    sa.Column('frozen_quantity', sa.Integer(), nullable=True, comment='冻结数量'),
    sa.Column('status', sa.Enum('active', 'closed', 'liquidated', name='positionstatus'), nullable=True, comment='持仓状态'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='开仓时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('closed_at', sa.DateTime(), nullable=True, comment='平仓时间'),
    sa.Column('extra', sa.JSON(), nullable=True, comment='扩展信息'),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_table('risk_checks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('order_no', sa.String(length=64), nullable=True, comment='订单号'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='股票代码'),
    sa.Column('direction', sa.String(length=20), nullable=False, comment='方向'),
    sa.Column('price', sa.Float(), nullable=False, comment='价格'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='数量'),
    sa.Column('risk_type', sa.Enum('position_limit', 'single_trade_limit', 'daily_limit', 'max_loss_limit', 'max_position_loss', 'position_percentage', 'risk_value', 'drawdown', name='risktype'), nullable=False, comment='检查类型'),
    sa.Column('limit_value', sa.Float(), nullable=True, comment='限额值'),
    sa.Column('actual_value', sa.Float(), nullable=True, comment='实际值'),
    sa.Column('passed', sa.Boolean(), nullable=False, comment='是否通过'),
    sa.Column('level', sa.Enum('normal', 'warning', 'danger', 'blocked', name='risklevel'), nullable=True, comment='风险等级'),
    sa.Column('message', sa.Text(), nullable=True, comment='检查信息'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='检查时间'),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_table('risk_limits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('limit_name', sa.String(length=100), nullable=False, comment='限额名称'),
    sa.Column('risk_type', sa.Enum('position_limit', 'single_trade_limit', 'daily_limit', 'max_loss_limit', 'max_position_loss', 'position_percentage', 'risk_value', 'drawdown', name='risktype'), nullable=False, comment='风险类型'),
    sa.Column('limit_value', sa.Float(), nullable=False, comment='限额值'),
    sa.Column('warning_value', sa.Float(), nullable=True, comment='警告值'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述'),
    sa.Column('enabled', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_table('risk_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('report_date', sa.DateTime(), nullable=False, comment='报告日期'),
    sa.Column('total_trades', sa.Integer(), nullable=True, comment='总交易笔数'),
    sa.Column('risk_alerts', sa.Integer(), nullable=True, comment='风险预警次数'),
    sa.Column('risk_blocked', sa.Integer(), nullable=True, comment='风控拦截次数'),
    sa.Column('total_position_value', sa.Float(), nullable=True, comment='总持仓市值'),
    sa.Column('total_pnl', sa.Float(), nullable=True, comment='总盈亏'),
    sa.Column('max_position_pct', sa.Float(), nullable=True, comment='最大持仓占比'),
    sa.Column('max_single_trade_pct', sa.Float(), nullable=True, comment='最大单笔占比'),
    sa.Column('daily_loss_limit', sa.Float(), nullable=True, comment='当日亏损限额'),
    sa.Column('current_daily_loss', sa.Float(), nullable=True, comment='当日累计亏损'),
    sa.Column('risk_value', sa.Float(), nullable=True, comment='在险价值 VaR'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='报告时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_date'),
    sqlite_autoincrement=True
    )
    op.create_table('stock_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='股票代码'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='股票名称'),
    sa.Column('exchange', sa.String(length=50), nullable=False, comment='交易所：SSE/SZSE/BSE'),
    sa.Column('sector', sa.String(length=100), nullable=True, comment='所属行业'),
    sa.Column('market_cap', sa.Float(), nullable=True, comment='总市值'),
    sa.Column('total_shares', sa.Float(), nullable=True, comment='总股本'),
    sa.Column('float_shares', sa.Float(), nullable=True, comment='流通股本'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sqlite_autoincrement=True
    )
    op.create_table('strategies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='策略名称'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='策略代码'),
    sa.Column('type', sa.String(length=50), nullable=False, comment='策略类型：technical/factor/grid'),
    sa.Column('description', sa.Text(), nullable=True, comment='策略描述'),
    sa.Column('params', sa.JSON(), nullable=False, comment='策略参数'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态：active/inactive/deleted'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('strategy_signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('strategy_id', sa.Integer(), nullable=False, comment='策略 ID'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='股票代码'),
    sa.Column('action', sa.String(length=20), nullable=False, comment='操作：buy/sell/hold'),
    sa.Column('price', sa.Float(), nullable=False, comment='触发价格'),
    sa.Column('quantity', sa.Integer(), nullable=True, comment='建议数量'),
    sa.Column('reason', sa.Text(), nullable=True, comment='信号理由'),
    sa.Column('strength', sa.Float(), nullable=True, comment='信号强度：0-1'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='信号产生时间'),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_table('trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('order_no', sa.String(length=64), nullable=False, comment='订单号'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='股票代码'),
    sa.Column('direction', sa.Enum('buy', 'sell', name='orderdirection'), nullable=False, comment='交易方向'),
    sa.Column('price', sa.Float(), nullable=False, comment='成交价格'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='成交数量'),
    sa.Column('commission', sa.Float(), nullable=True, comment='佣金'),
    sa.Column('slip', sa.Float(), nullable=True, comment='滑点'),
    sa.Column('submit_time', sa.DateTime(), nullable=True, comment='提交时间'),
    sa.Column('trade_time', sa.DateTime(), nullable=True, comment='成交时间'),
    sa.Column('extra', sa.JSON(), nullable=True, comment='扩展信息'),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='用户名'),
    sa.Column('email', sa.String(length=100), nullable=False, comment='邮箱'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='密码哈希'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('is_admin', sa.Boolean(), nullable=True, comment='是否管理员'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('last_login_at', sa.DateTime(), nullable=True, comment='最后登录时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('trades')
    op.drop_table('strategy_signals')
    op.drop_table('strategies')
    op.drop_table('stock_info')
    op.drop_table('risk_reports')
    op.drop_table('risk_limits')
    op.drop_table('risk_checks')
    op.drop_table('positions')
    op.drop_table('orders')
    op.drop_table('market_data')
    op.drop_table('equity_curves')
    op.drop_table('calendar')
    op.drop_table('backtests')
    op.drop_table('backtest_trades')
    op.drop_table('backtest_results')
    op.drop_table('accounts')
    op.drop_table('account_logs')
    # ### end Alembic commands ###
