"""
通用模块
提供共享的工具、配置和模型
"""
from .config import settings, Settings, get_settings, get_database_url, is_production, is_development, is_testing
from .database import get_db, engine, SessionLocal, Base, init_db, check_db_connection, get_db_info
from .redis_client import redis_client, get_redis, check_redis_connection, get_redis_info, RedisCache, market_cache, strategy_cache, portfolio_cache
from .message_queue import MessageQueue, market_data_queue, trading_signal_queue, portfolio_update_queue
from .logging import setup_logging, get_logger, ContextLogger, request_id_var, user_id_var
from .exceptions import (
    QuantBaseException,
    DataException,
    StrategyException,
    TradingException,
    RiskException,
    BacktestException,
    PortfolioException,
    ValidationException,
    NotFoundException,
    PermissionException,
    quant_exception_handler,
    general_exception_handler,
    raise_not_found,
    raise_validation_error,
    raise_data_error,
    raise_strategy_error,
    raise_trading_error,
    raise_risk_error,
    raise_backtest_error,
    raise_portfolio_error,
)
from .middleware import RequestMiddleware, PerformanceMiddleware, CORSMiddleware
from .validation import (
    BaseRequest,
    PaginationRequest,
    StockCodeRequest,
    DateRangeRequest,
    OrderCreateRequest,
    OrderQueryRequest,
    StrategyCreateRequest,
    StrategyUpdateRequest,
    BacktestCreateRequest,
    RiskLimitCreateRequest,
    MarketDataQueryRequest,
    PortfolioSummaryRequest,
    RiskCheckRequest,
    PaginationResponse,
    OrderResponse,
    StrategyResponse,
    BacktestResponse,
    RiskLimitResponse,
    PositionResponse,
    AccountResponse,
    HealthResponse,
    ErrorResponse,
)
from .health import (
    HealthStatus,
    HealthCheckResult,
    ComponentHealth,
    HealthChecker,
    MetricsCollector,
    get_health_checker,
    get_metrics_collector,
)
from .auth import (
    auth_service,
    AuthService,
    permission_checker,
    PermissionChecker,
    UserRole,
    Permission,
    PasswordHasher,
    TokenManager,
    User as AuthUser,
)
from .auth_dependency import get_current_user, get_optional_user, bearer_scheme
from .auth_router import router as auth_router
from .scheduler import scheduler, Scheduler
from .ws import connection_manager, ConnectionManager, create_ws_endpoint

__all__ = [
    # 配置
    "settings",
    "Settings",
    "get_settings",
    "get_database_url",
    "is_production",
    "is_development",
    "is_testing",
    # 数据库
    "get_db",
    "engine",
    "SessionLocal",
    "Base",
    "init_db",
    "check_db_connection",
    "get_db_info",
    # Redis
    "redis_client",
    "get_redis",
    "check_redis_connection",
    "get_redis_info",
    "RedisCache",
    "market_cache",
    "strategy_cache",
    "portfolio_cache",
    # 消息队列
    "MessageQueue",
    "market_data_queue",
    "trading_signal_queue",
    "portfolio_update_queue",
    # 日志
    "setup_logging",
    "get_logger",
    "ContextLogger",
    "request_id_var",
    "user_id_var",
    # 异常
    "QuantBaseException",
    "DataException",
    "StrategyException",
    "TradingException",
    "RiskException",
    "BacktestException",
    "PortfolioException",
    "ValidationException",
    "NotFoundException",
    "PermissionException",
    "quant_exception_handler",
    "general_exception_handler",
    "raise_not_found",
    "raise_validation_error",
    "raise_data_error",
    "raise_strategy_error",
    "raise_trading_error",
    "raise_risk_error",
    "raise_backtest_error",
    "raise_portfolio_error",
    # 中间件
    "RequestMiddleware",
    "PerformanceMiddleware",
    "CORSMiddleware",
    # 验证
    "BaseRequest",
    "PaginationRequest",
    "StockCodeRequest",
    "DateRangeRequest",
    "OrderCreateRequest",
    "OrderQueryRequest",
    "StrategyCreateRequest",
    "StrategyUpdateRequest",
    "BacktestCreateRequest",
    "RiskLimitCreateRequest",
    "MarketDataQueryRequest",
    "PortfolioSummaryRequest",
    "RiskCheckRequest",
    "PaginationResponse",
    "OrderResponse",
    "StrategyResponse",
    "BacktestResponse",
    "RiskLimitResponse",
    "PositionResponse",
    "AccountResponse",
    "HealthResponse",
    "ErrorResponse",
    # 健康检查和监控
    "HealthStatus",
    "HealthCheckResult",
    "ComponentHealth",
    "HealthChecker",
    "MetricsCollector",
    "get_health_checker",
    "get_metrics_collector",
    # 认证
    "auth_service",
    "AuthService",
    "permission_checker",
    "PermissionChecker",
    "UserRole",
    "Permission",
    "PasswordHasher",
    "TokenManager",
    "AuthUser",
    "get_current_user",
    "get_optional_user",
    "bearer_scheme",
    "auth_router",
    # 定时任务
    "scheduler",
    "Scheduler",
    # WebSocket
    "connection_manager",
    "ConnectionManager",
    "create_ws_endpoint",
]